wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.1
    start_time: 1642256240
    t:
      3:
      - 2
      4: 3.10.1
      5: 0.12.9
      8:
      - 5
